Including 12.72 monsters
opentibiabr/otservbr-global pull request #448
Opened 2022-02-24 00:26 UTC by guispiller

# Description

This PR is to include some missing monsters from Tibia 12.72 version, with their lua script, spells and prey/bestiary inclusion.
I tried to replicate all of the combat features from the creatures, following youtube videos and informations from https://tibia.fandom.com/wiki.

Please delete options that are not relevant.

  - [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

  - [X] Summoning all monsters to check spells and appearences
  - [X] Killing all monsters to check body and loot

**Test Configuration**:

  - Server Version: 1.2.0
  - Client: 12.85
  - Operating System: Windows 10

## Checklist

  - [X] My code follows the style guidelines of this project
  - [X] I have performed a self-review of my own code
  - [X] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [X] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

2022-02-24 00:29 UTC, MajestyOTBR commented
Good pull request, thanks for your contribution.
Anyone to help to test?

2022-02-28 17:23 UTC, MajestyOTBR approved these changes

2022-02-28 17:29 UTC, MajestyOTBR commented on data/monster/humans/carnisylvan_sapling.lua
> +monster.corpse = 41720
Check corpse id.

2022-02-28 17:32 UTC, MajestyOTBR commented on data/monster/magicals/bashmu.lua
> +monster.corpse = 36804
Need to register corpse id on items.xml

2022-02-28 17:33 UTC, MajestyOTBR commented on data/monster/magicals/girtablilu_warrior.lua
> +monster.corpse = 36800
Need to register corpse id on items.xml

2022-02-28 17:34 UTC, MajestyOTBR commented on data/monster/magicals/juvenile_bashmu.lua
> +
Line contains only whitespace

2022-02-28 17:34 UTC, MajestyOTBR commented on data/monster/magicals/juvenile_bashmu.lua
> +monster.corpse = 36967
Need to register corpse id on items.xml

2022-02-28 17:35 UTC, MajestyOTBR commented on data/monster/magicals/venerable_girtablilu.lua
> +monster.corpse = 36963
Need to register corpse id on items.xml

2022-02-28 17:35 UTC, MajestyOTBR commented on data/monster/magicals/venerable_girtablilu.lua
> +	{name = "violet crystal shard", chance = 2530},
Line contains trailing whitespace

2022-02-28 17:36 UTC, MajestyOTBR commented on data/monster/magicals/venerable_girtablilu.lua
> +	{name = "wand of defiance", chance = 1340},
Line contains trailing whitespace

2022-02-28 17:37 UTC, MajestyOTBR commented on data/monster/vermins/afflicted_strider.lua
> +
Line contains only whitespace

2022-02-28 17:37 UTC, MajestyOTBR commented on data/monster/vermins/afflicted_strider.lua
> +
Line contains only whitespace

2022-02-28 17:39 UTC, MajestyOTBR commented on data/monster/vermins/lavafungus.lua
> +
Line contains only whitespace

2022-02-28 17:41 UTC, MajestyOTBR commented on data/scripts/spells/monster/sapling_explode.lua
> +	local from = creature:getId()
Unused variable 'from'

2022-02-28 18:13 UTC, MajestyOTBR requested changes
Check warnings and register corpse ids on items.xml.

2022-03-03 21:46 UTC, MajestyOTBR approved these changes

2022-03-09 11:29 UTC, merged

2022-03-12 22:08 UTC, garaflaks commented
is there the map with the added monsters?