Fix Amulet bug in enchanted werewolf amulet time and skill cobra crossbow and enchanted theurgic amulet
opentibiabr/otservbr-global pull request #514
Opened 2022-03-21 00:50 UTC by painer15999

# Description

Amulet bug fix in enchanted werewolf amulet, enchanted theurgic amulet, time result (onDeEquip) and skill bug.
& register attirbutes cobra crossbow.

## Behaviour
### **Actual**

This PR is to fix amulets enchanted werewolf amulet, enchanted theurgic amulet and cobra crossbow

### **Expected**

Equip and unequip enchanted werewolf amulet or enchanted theurgic amulet and the time will now decrease as expected, and cobra crossbow attributes corresponding.

## Type of change

Please delete options that are not relevant.

  - [x] Bug fix (non-breaking change which fixes an issue)
  - [x] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

  - [x] Test A
  - [x] Test B

**Test Configuration**:

  - Server Version: Main
  - Client: 12.85
  - Operating System:  Windows 10 / Ubuntu 20.4

## Checklist

  - [x] My code follows the style guidelines of this project
  - [x] I have performed a self-review of my own code
  - [x] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [x] My changes generate no new warnings
  - [x] I have added tests that prove my fix is effective or that my feature works

2022-03-21 04:46 UTC, dudantas requested changes
I added some suggestions to fix the indentation. It's just commit.

2022-03-21 04:46 UTC, dudantas commented on data/items/items.xml
> +        <attribute key="weaponType" value="distance"/>
```suggestion
	<item id="30393" article="a" name="cobra crossbow">
		<attribute key="weaponType" value="distance"/>
```

2022-03-21 04:46 UTC, dudantas commented on data/items/items.xml
> +        <attribute key="ammotype" value="bolt"/>
```suggestion
		<attribute key="ammotype" value="bolt"/>
```

2022-03-28 23:23 UTC, MajestyOTBR commented
Update your branch and commit the suggested changes.

2022-04-01 11:09 UTC, MajestyOTBR approved these changes

2022-04-04 21:16 UTC, dudantas approved these changes

2022-04-04 21:29 UTC, merged