Update levitate.lua
opentibiabr/otservbr-global pull request #523
Opened 2022-03-30 19:29 UTC by travisani

Changes Proposed
make levitate and parcel behaviour more accurate
remove floorchange check from levitate, replace checked tilestate to immovableblocksolid
needs testing

expected behaviour:

POSSIBLE: levitating/parcel walking to tiles blocked by furniture
POSSIBLE: levitating/parcel walking to tiles like 459
NOT POSSIBLE: levitating/parcel walking to walls, immovable obstacles or unwalkable grounds
NOT POSSIBLE levitating/parcel walking to tiles with PVP magic walls

~~~~

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Behaviour
### **Actual**

Do this and that doesn't happens

### **Expected**

Do this and that happens

## Fixes

\# (issue)

## Type of change

Please delete options that are not relevant.

  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

  - [ ] Test A
  - [ ] Test B

**Test Configuration**:

  - Server Version:
  - Client:
  - Operating System:

## Checklist

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

2022-03-30 19:41 UTC, travisani commented
Need to change in src/game/game.cpp


```
				if (tmpTile && tmpTile->getGround() && !tmpTile->hasFlag(TILESTATE_BLOCKSOLID)) {
to
				if (tmpTile && tmpTile->getGround() && !tmpTile->hasFlag(TILESTATE_IMMOVABLEBLOCKSOLID)) {
```


and

```
				if (tmpTile && tmpTile->hasHeight(3)) {
to
				if (tmpTile && tmpTile->hasHeight(3) && !tmpTile->hasFlag(TILESTATE_IMMOVABLEBLOCKSOLID)) {
```

2022-04-01 11:15 UTC, MajestyOTBR commented
> **Need to change in src/game/game.cpp**
> 
> ```
> 				if (tmpTile && tmpTile->getGround() && !tmpTile->hasFlag(TILESTATE_BLOCKSOLID)) {
> to
> 				if (tmpTile && tmpTile->getGround() && !tmpTile->hasFlag(TILESTATE_IMMOVABLEBLOCKSOLID)) {
> ```
> 
> and
> 
> ```
> 				if (tmpTile && tmpTile->hasHeight(3)) {
> to
> 				if (tmpTile && tmpTile->hasHeight(3) && !tmpTile->hasFlag(TILESTATE_IMMOVABLEBLOCKSOLID)) {
> ```

For source changes, create a pull request in Canary repository:
https://github.com/opentibiabr/canary

2022-04-04 21:40 UTC, dudantas requested changes

2022-04-04 21:40 UTC, dudantas commented on data/scripts/spells/support/levitate.lua
>  end
Please fix the indentation:
```suggestion
		creature:getPosition():sendMagicEffect(CONST_ME_POFF)
		return false
	end
	return true
end
```

2022-04-04 21:40 UTC, dudantas commented on data/scripts/spells/support/levitate.lua
> +				return moved
Remove trailing whitespace:
```suggestion
				return moved
```

2022-05-27 18:27 UTC, majestyotbr commented
Closed due to inactivity.

2022-05-27 18:27 UTC, closed without merging