Remove unsafe addEvent
opentibiabr/otservbr-global pull request #536
Opened 2022-04-06 19:06 UTC by andersonfaaria

- Removed AddEvent from two functions of store
- Corrected cults of tibia wall id

2022-04-07 13:04 UTC, guispiller requested changes
When buying Kegs or Decoration Kits, it's not "transforming" the parcel nor the wrapped box into the needed item. It's being just an empty parcel, and a closed box.

2022-04-07 20:41 UTC, guispiller approved these changes

2022-04-22 18:51 UTC, dudantas approved these changes

2022-04-22 18:51 UTC, MajestyOTBR approved these changes

2022-04-22 18:52 UTC, merged