[Enhancement] Rework on fluids colors + new monster race type (INK)
opentibiabr/otservbr-global pull request #544
Opened 2022-04-19 20:30 UTC by marcosvf132

# Description
- Full rework on the way that the server handles the fluids, to use one single ENUM and remove all the garbage functions and maps that used to store the same values for fluids over and over again.
- Add new creature race type named INK. This new race type is used mostly on creatures on the tibia **_"The Secret Library"_**. Attacking those creatures or slain then will now create the proper type of blood pool/splash.

## Sync
This PR only will work when using with Canary https://github.com/opentibiabr/canary/pull/324 changes.

2022-04-20 08:00 UTC, andersonfaaria approved these changes

2022-04-23 15:10 UTC, MajestyOTBR approved these changes

2022-04-23 15:11 UTC, guispiller requested changes, later dismissed
Missing fix on npcs that sells fluids

2022-04-25 19:35 UTC, majestyotbr approved these changes

2022-04-25 20:36 UTC, merged