New frontier quest Review & Fix
opentibiabr/otservbr-global pull request #594
Opened 2022-05-16 18:58 UTC by sircurse

# Description

Revised the entire quest, making elevators working again, moved many scripts to the unique folder data/scripts/quest/the_new_frontier

Rewrite of the entire questlog with the global version, rebuild all the tracking IDs to match exactly when it gets updated based on the global.

Revised all the NPCs, including new phrases based on the global and fixed some NPCs that was just not working as expected.
Removed some unnecessary scripts and changed scripts that was dependent from map AID and UID, now everything should be running thru tables, easy to manage and fix in future.

Please delete options that are not relevant.

  - [] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

  - [X] Full quest tested in internal server before submitting PR.

## Checklist

  - [X] My code follows the style guidelines of this project
  - [X] I have performed a self-review of my own code
  - [] I checked the PR checks reports
  - [X] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [X] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

2022-06-16 00:33 UTC, guispiller requested changes
There are two old scipts that are in conflict with the new ones and need to be deleted, on data/scripts/creaturescripts/quests/the_new_frontier.
Besides that, everything is 100%, good job.

2022-06-20 19:44 UTC, majestyotbr approved these changes

2022-06-20 19:45 UTC, guispiller approved these changes

2022-06-20 21:48 UTC, merged

2022-06-20 21:49 UTC, majestyotbr commented
Thanks for your contribution!

2022-06-20 21:49 UTC, majestyotbr commented
Updated otservbr-global map available in:
https://majestyotbr.gitbook.io/opentibiabr/projects/otservbr-global#updated-otservbr-global-map