Fix magic wall rune bug
opentibiabr/otservbr-global pull request #601
Opened 2022-05-23 06:24 UTC by dudantas

Working with: https://github.com/opentibiabr/canary/pull/388

Fixed magic wall rune (bug related to wrong flag "blocking")

2022-05-23 17:08 UTC, Alissonlv123 commented
Aprovado Rodou Tranquilo E funcionando perfeitamente!

2022-05-23 17:21 UTC, Alissonlv123 approved these changes

2022-05-23 21:19 UTC, guispiller requested changes

2022-05-23 21:19 UTC, guispiller commented on data/scripts/spells/runes/wild_growth.lua
> +		wildGrowth = ITEM_MAGICWALL_SAFE
wildGrowth = ITEM_WILDGROWTH_SAFE

2022-05-23 21:19 UTC, guispiller commented on data/scripts/spells/runes/wild_growth.lua
> +		wildGrowth = ITEM_MAGICWALL
wildGrowth = ITEM_WILDGROWTH

2022-05-23 21:19 UTC, guispiller commented on data/scripts/spells/runes/wild_growth.lua
> +combat:setParameter(COMBAT_PARAM_DISTANCEEFFECT, CONST_ANI_EARTH)
combat:setParameter(COMBAT_PARAM_DISTANCEEFFECT, CONST_ANI_ENERGY)

2022-05-23 21:32 UTC, guispiller approved these changes

2022-05-24 18:03 UTC, omeranha approved these changes

2022-05-26 08:32 UTC, majestyotbr approved these changes

2022-05-26 17:44 UTC, merged