Rework & added threatened dreams quest
opentibiabr/otservbr-global pull request #633
Opened 2022-06-03 19:48 UTC by sircurse

Rework of the initial quest that give access to Feyrist area and added additional quests to the story line.

## Type of change

Please delete options that are not relevant.

  - [X] Bug fix (non-breaking change which fixes an issue)
  - [X] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How Has This Been Tested

The scripts was tested by me and players from my server.

## Checklist

  - [X] My code follows the style guidelines of this project
  - [X] I have performed a self-review of my own code
  - [X] I checked the PR checks reports
  - [X] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [X] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

2022-06-16 02:20 UTC, guispiller requested changes
Small changes on typos.

There's also a script that's conflicting with another you created: data/scripts/movements/quests/feyrist/kroazur_entrance.lua

2022-06-16 02:20 UTC, guispiller commented on data/lib/core/storages.lua
> +				DarkMoomMirror = 50286,
fix Typo "moon" here and in other scripts

2022-06-16 02:20 UTC, guispiller commented on data/lib/core/storages.lua
> +				SunCactherPos05 = 50304,
fix typo "catcher" in this 6 storages above and in other scripts

2022-06-16 02:20 UTC, guispiller commented on data/lib/core/storages.lua
> +				SunCactherPos05 = 50304,
fix typo "catcher" in this 6 storages above

2022-06-16 02:20 UTC, guispiller commented on data/startup/tables/tile.lua
>  	[50301] = {
this AIDs from 50301 to 50305  should be removed, they are conflicting with the new ones

2022-06-16 02:20 UTC, guispiller commented on data/startup/tables/tile.lua
>  	[50301] = {
this AIDs should be removed, they are conflicting with the new ones

2022-06-22 22:51 UTC, majestyotbr approved these changes

2022-06-23 13:58 UTC, guispiller requested changes

2022-06-23 13:58 UTC, guispiller commented on data/lib/core/storages.lua
> +					ChargedMoomMirror = 75774,
There's just this storage left to fix typos, the rest is fine. Fix typo "moom" here, and on scripts that have this same storage.

2022-06-23 14:28 UTC, guispiller approved these changes

2022-06-23 15:05 UTC, majestyotbr approved these changes

2022-06-23 15:06 UTC, merged

2022-06-23 15:06 UTC, majestyotbr commented
Thanks for your contribution!

2022-06-23 15:07 UTC, majestyotbr commented
Updated otservbr-global map available in:
https://majestyotbr.gitbook.io/opentibiabr/projects/otservbr-global#updated-otservbr-global-map