Create goldchanger.lua
opentibiabr/otservbr-global pull request #644
Opened 2022-06-10 23:38 UTC by travisani

Add a Custom gold changer.
Change Crystal to platinum and Platinum to Gold.

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Behaviour
### **Actual**

Do this and that doesn't happens

### **Expected**

Do this and that happens

## Fixes

\# (issue)

## Type of change

Please delete options that are not relevant.

  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

  - [ ] Test A
  - [ ] Test B

**Test Configuration**:

  - Server Version:
  - Client:
  - Operating System:

## Checklist

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

2022-06-11 18:19 UTC, guispiller approved these changes

2022-06-11 20:55 UTC, majestyotbr commented
Change the file name to change_gold.lua.

2022-06-11 23:33 UTC, daanyx approved these changes

2022-06-12 16:32 UTC, guispiller approved these changes

2022-06-13 22:34 UTC, majestyotbr approved these changes

2022-06-15 03:59 UTC, dudantas commented on data/scripts/actions/other/change_gold.lua
> +changeGold:register()
I think we can improve a little, indicate for tab and removing unecessary "else"

```suggestion
local config = {
	[ITEM_GOLD_COIN] = {changeTo = ITEM_PLATINUM_COIN},
	[ITEM_PLATINUM_COIN] = {changeBack = ITEM_GOLD_COIN, changeTo = ITEM_CRYSTAL_COIN},
	[ITEM_CRYSTAL_COIN] = {changeBack = ITEM_PLATINUM_COIN}
}

local changeGold = Action()
function changeGold.onUse(player, item, fromPosition, target, toPosition, isHotkey)
	local coin = config[item:getId()]
	if coin.changeTo and item.type == 100 then
		item:remove()
		player:addItem(coin.changeTo, 1)
		return true
	elseif coin.changeBack then
		item:remove(1)
		player:addItem(coin.changeBack, 100)
		return true
	end
	return false
end

changeGold:id(3031, 3035, 3043)
changeGold:register()
```

2022-06-24 01:17 UTC, omeranha requested changes
I would recommend move the file to custom folder for better management, thank you

2022-07-02 22:12 UTC, omeranha approved these changes

2022-07-02 22:13 UTC, guispiller approved these changes

2022-07-02 23:54 UTC, merged