enable gamestore to offers services/items for tournament coins
opentibiabr/otservbr-global pull request #743
Opened 2022-08-04 01:27 UTC by bosmak

# Description

Allows offers tagged with `coinType = GameStore.CointType.Tournament` to correctly charge Tournament Coins.
Added correct history for the store transactions following the coin type.
Removed duplicate charge and history when changing the Name or Sex of a Hireling.

## Behaviour
### **Actual**

Buying something tagged with Tournament Coins will be charged on Tibia Coins.

Buying `Hireling Sex Change` or `Hireling Name Change` charges twice the amount and add two purchases to the history.

### **Expected**

Buying something tagged with Tournament Coins will be charged using Tournament Coins.

Buying `Hireling Sex Change` or `Hireling Name Change` charges the displayed amount and adds a single purchase to the history.

## Fixes

\# (issue)

## Type of change

Please delete options that are not relevant.

  - [X] Bug fix (non-breaking change which fixes an issue)
  - [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested

On `data/modules/scripts/gamestore/gamestore.lua` change the line 4492 from `offer.coinType = GameStore.CointType.Coin` to `offer.coinType = GameStore.CointType.Tournament` to change all offers to use Tournament Coins.

Go inside the game and buy one of each OfferType; check history.

**Test Configuration**:

  - Server Version: Canary@5a6da6c1436be0d4a0a9b06a7a9d2fb98325eb3f
  - Client: 12.86.11871
  - Operating System: Ubuntu:21.04

## Checklist

  - [X] My code follows the style guidelines of this project
  - [X] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

2022-08-05 15:33 UTC, QuebradaZN commented
After making a purchase using Tournament Coins, you are not debited from Tournament Points but from Tibia Coins

2022-08-07 20:26 UTC, majestyotbr approved these changes

2022-08-07 23:41 UTC, majestyotbr approved these changes

2022-08-08 16:07 UTC, dudantas requested changes
Some suggestions related to indentation. The code itself seems to be ok.

2022-08-08 16:07 UTC, dudantas commented on data/migrations/19.lua
> +    db.query("ALTER TABLE `store_history` DROP COLUMN `coins`") -- Not in use anywhere.
```suggestion
	db.query("ALTER TABLE `store_history` DROP COLUMN `coins`") -- Not in use anywhere.
```

2022-08-08 16:07 UTC, dudantas commented on data/migrations/20.lua
> +end
```suggestion
end

```

2022-08-08 16:07 UTC, dudantas commented on data/modules/scripts/gamestore/init.lua
> +
```suggestion

```

2022-08-08 16:07 UTC, dudantas commented on data/modules/scripts/gamestore/init.lua
> +	msg:addU32(0) 							  -- How many are reserved for a Character Auction
```suggestion
	msg:addU32(player:getCoinsBalance()) -- Tibia Coins
	msg:addU32(player:getCoinsBalance()) -- How many are Transferable
	msg:addU32(0) -- How many are reserved for a Character Auction
```

2022-08-08 16:07 UTC, dudantas commented on data/modules/scripts/gamestore/init.lua
> +
```suggestion

```

2022-08-08 16:07 UTC, dudantas commented on data/modules/scripts/gamestore/init.lua
> +	if not resultId then return 0 end
```suggestion
	if not resultId then
		return 0
	end
```

2022-08-08 16:07 UTC, dudantas commented on data/modules/scripts/gamestore/init.lua
> +
```suggestion

```

2022-08-08 16:07 UTC, dudantas commented on data/modules/scripts/gamestore/init.lua
> +		--player:showInfoModal('Info',string.format('%s has been renamed to %s', oldName, newHirelingName))
```suggestion
		Spdlog.debug(string.format('%s has been renamed to %s', oldName, newHirelingName))
```

2022-08-08 16:07 UTC, dudantas commented on data/modules/scripts/gamestore/init.lua
> +		--player:showInfoModal('Info',string.format('%s sex was changed to %s', hireling:getName(), sexString))
```suggestion
		Spdlog.debug(string.format('%s sex was changed to %s', hireling:getName(), sexString))
```

2022-08-08 16:07 UTC, dudantas commented on schema.sql
> +  `recruiter`           INT(6)        DEFAULT 0,
```suggestion
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(32) NOT NULL,
  `password` char(40) NOT NULL,
  `email` varchar(255) NOT NULL DEFAULT '',
  `premdays` int(11) NOT NULL DEFAULT '0',
  `lastday` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `type` tinyint(1) UNSIGNED NOT NULL DEFAULT '1',
  `coins` int(12) UNSIGNED NOT NULL DEFAULT '0',
  `tournament_coins` int(12) UNSIGNED NOT NULL DEFAULT '0',
  `creation` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `recruiter` INT(6) DEFAULT 0,
```

2022-08-08 16:07 UTC, dudantas commented on schema.sql
> +) ENGINE = InnoDB DEFAULT CHARSET = utf8;
```suggestion
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`account_id` int(11) UNSIGNED NOT NULL,
	`mode` smallint(2) NOT NULL DEFAULT '0',
	`description` varchar(3500) NOT NULL,
	`coin_type` tinyint(1) NOT NULL DEFAULT '0',
	`coin_amount` int(12) NOT NULL,
	`time` bigint(20) UNSIGNED NOT NULL,
	`timestamp` int(11) NOT NULL DEFAULT '0',
	INDEX `account_id` (`account_id`),
	CONSTRAINT `store_history_pk`
		PRIMARY KEY (`id`),
	CONSTRAINT `store_history_account_fk`
		FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`)
		ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
```

2022-08-08 17:11 UTC, dudantas approved these changes

2022-08-08 17:21 UTC, majestyotbr approved these changes

2022-08-08 21:53 UTC, guispiller approved these changes

2022-08-10 14:44 UTC, JoaoCRDias approved these changes

2022-08-10 16:13 UTC, QuebradaZN approved these changes
Testing and apparently everything is ok!

2022-08-10 17:26 UTC, merged