Fix Forgotten Knowledge Bosses
opentibiabr/otservbr-global pull request #783
Opened 2022-09-08 15:31 UTC by murilo09

# Description

Fix Lloyd fight and Forgotten Knowledge bosses time

Remove AID from positions: 
- [x] 33391, 31177, 10
- [x] 32019, 32843, 14
- [x] 32302, 31087, 14
- [x] 32657, 32876, 14
- [x] 32759, 32867, 14
- [x] 32902, 31622, 14
- [x] 33010, 31659, 14

## Behaviour
### **Actual**

Can kill any prism in Lloyd fight

### **Expected**

Now Lloyd is working as expected

## Fixes

#285 
#363 

## Type of change

Please delete options that are not relevant.

  - [x] New feature (non-breaking change which adds functionality)

## Checklist

  - [X] My code follows the style guidelines of this project
  - [X] I have performed a self-review of my own code
  - [X] I checked the PR checks reports
  - [X] My changes generate no new warnings

2022-09-17 21:20 UTC, murilo09 commented
Drafted while the other bosses are not ready

2022-09-19 23:37 UTC, majestyotbr approved these changes

2022-09-21 01:51 UTC, dudantas requested changes

2022-09-21 01:51 UTC, dudantas commented on data/scripts/creaturescripts/quests/forgotten_knowledge/melting_death.lua
> +    if creature:isMonster() and creature:getName():lower() ~= 'melting frozen horror' then
```suggestion
    if not creature then
        return
    end
   
    if creature:isMonster() and creature:getName():lower() ~= 'melting frozen horror' then
```

2022-09-21 01:51 UTC, dudantas commented on data/scripts/actions/quests/forgotten_knowledge/dragonking_lever.lua
>  forgottenKnowledgeDragonking:register()
```suggestion
forgottenKnowledgeDragonking:register()

```

2022-09-21 01:51 UTC, dudantas commented on data/scripts/actions/quests/forgotten_knowledge/horror_lever.lua
>  forgottenKnowledgeHorror:register()
```suggestion
forgottenKnowledgeHorror:register()

```

2022-09-21 01:51 UTC, dudantas commented on data/scripts/actions/quests/forgotten_knowledge/tenebris_lever.lua
>  forgottenKnowledgeTenebris:register()
```suggestion
forgottenKnowledgeTenebris:register()

```

2022-09-21 01:51 UTC, dudantas commented on data/scripts/actions/quests/forgotten_knowledge/thorn_knight_lever.lua
>  forgottenKnowledgeThorn:register()
```suggestion
forgottenKnowledgeThorn:register()

```

2022-09-21 01:51 UTC, dudantas commented on data/scripts/actions/quests/forgotten_knowledge/time_guardian_lever.lua
>  forgottenKnowledgeGuardianLever:register()
```suggestion
forgottenKnowledgeGuardianLever:register()

```

2022-09-21 01:51 UTC, dudantas commented on data/scripts/creaturescripts/quests/forgotten_knowledge/energy_prism_death.lua
> +energyPrismDeath:register()
```suggestion
energyPrismDeath:register()

```

2022-09-21 01:51 UTC, dudantas commented on data/scripts/creaturescripts/quests/forgotten_knowledge/lloyd_preparedeath.lua
> +    if not targetMonster then
```suggestion
    if not creature or not targetMonster then
```

2022-09-24 15:19 UTC, dudantas commented on data/scripts/creaturescripts/quests/forgotten_knowledge/lloyd_preparedeath.lua
> +    end
```suggestion
local function revertLloyd(prismId)
	local lloydTile = Tile(Position(32799, 32826, 14))
	if lloydTile then
		local lloyd = lloydTile:getTopCreature()
		lloyd:teleportTo(Position(32799, 32829, 14))
		lloyd:getPosition():sendMagicEffect(CONST_ME_TELEPORT)
	end
```

2022-09-24 15:19 UTC, dudantas commented on data/scripts/creaturescripts/quests/forgotten_knowledge/lloyd_preparedeath.lua
> +    {cosmicNormal = 'cosmic energy prism d', cosmicInvu = 'cosmic energy prism d invu', pos = Position(32796, 32826, 14)}
```suggestion
	{cosmicNormal = 'cosmic energy prism a', cosmicInvu = 'cosmic energy prism a invu', pos = Position(32801, 32827, 14)},
	{cosmicNormal = 'cosmic energy prism b', cosmicInvu = 'cosmic energy prism b invu', pos = Position(32798, 32827, 14)},
	{cosmicNormal = 'cosmic energy prism c', cosmicInvu = 'cosmic energy prism c invu', pos = Position(32803, 32826, 14)},
	{cosmicNormal = 'cosmic energy prism d', cosmicInvu = 'cosmic energy prism d invu', pos = Position(32796, 32826, 14)}
```

2022-09-24 15:19 UTC, dudantas commented on data/scripts/creaturescripts/quests/forgotten_knowledge/lloyd_preparedeath.lua
> +    Game.createMonster(monsters[prismId].cosmicInvu, Position(monsters[prismId].pos), true, true)
```suggestion
	Tile(monsters[prismId].pos):getTopCreature():remove()
	Game.createMonster(monsters[prismId].cosmicInvu, Position(monsters[prismId].pos), true, true)
```

2022-09-24 15:19 UTC, dudantas commented on data/scripts/creaturescripts/quests/forgotten_knowledge/lloyd_preparedeath.lua
> +    end
```suggestion
	local targetMonster = creature:getMonster()
	if not creature or not targetMonster then
		return true
	end
```

2022-09-24 15:22 UTC, dudantas commented on data/scripts/actions/quests/forgotten_knowledge/dragonking_lever.lua
> +    lever:setCondition(function(creature)
Where does this creature come from?

2022-09-24 15:31 UTC, dudantas approved these changes

2022-10-01 17:55 UTC, merged