Fix Mr Morris Tasks
opentibiabr/otservbr-global pull request #784
Opened 2022-09-13 02:17 UTC by murilo09

# Description

Fix Mr Morris Tasks

## Behaviour
### **Actual**

Any monster killed was being counted in the task

### **Expected**

Only the right monster is being counted in the task

## Fixes

Reported on Discord

## Type of change

Please delete options that are not relevant.

  - [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested

## Checklist

  - [X] My code follows the style guidelines of this project
  - [X] I have performed a self-review of my own code
  - [X] I checked the PR checks reports
  - [X] My changes generate no new warnings

2022-09-13 03:51 UTC, dudantas requested changes

2022-09-13 03:51 UTC, dudantas commented on data/scripts/creaturescripts/quests/dawnport/troll_kill.lua
> +trollKill:register()
```suggestion
trollKill:register()

```

2022-09-13 03:51 UTC, dudantas commented on data/scripts/creaturescripts/quests/dawnport/goblin_kill.lua
> +goblinKill:register()
```suggestion
goblinKill:register()

```

2022-09-13 03:51 UTC, dudantas commented on data/scripts/creaturescripts/quests/dawnport/minotaur_kill.lua
> +minotaurKill:register()
```suggestion
minotaurKill:register()

```

2022-09-13 23:53 UTC, Gansoti approved these changes

2022-09-17 20:50 UTC, majestyotbr approved these changes

2022-09-21 02:10 UTC, dudantas commented on data/npc/mr_morris.lua
> +npcType:register(npcConfig)
```suggestion
npcType:register(npcConfig)

```

2022-09-30 21:39 UTC, merged